
What is Server Side Swift?
If you have a ToDo App, the device has a local database.
So you can store your data into local database or store them into Cloud! But if you store your datas into your local device and you lost your device,
All of your data will lost.
So it's better to store your data into the Cloud.

What is a Cloud!? -> Store your data into a server

Cloud-Kit of Apple
Firebase of Google
Parse of Facebook
Or other third parties.

Implement the Servers:
NodeJS
ASP.NET
PHP
dJango - Phyton
Rubby Language -> Rails
Finaly -> *** Swift

ServerSide Frameworks:
KITURA Framework (IBM) use Swift language to implement the ServerSide concepts and run.
VAPOR framework for Swift Programmers
Perfect.org
 ZeWC

 
